version: 0.2

phases:
  pre_build:
    commands:
      - aws --version
      - REPOSITORY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

  build:
    commands:
      - docker build -t ${ECR_REPO_NAME}:latest .
      - docker tag ${ECR_REPO_NAME}:latest ${REPOSITORY_URI}:latest

  post_build:
    commands:
      - docker push ${REPOSITORY_URI}:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' "${ECR_REPO_NAME}" "${REPOSITORY_URI}:latest" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
